# If you do not have OpenSSL installed, change the following line to use 'http://'
source 'https://rubygems.org'
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'byebug'
